name: Deploy to Github Pages
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
  
      - name: build lastest
        run: |
          npm ci
          npm run build
  
      - name: deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
          force_orphan: true
